### ISSUE TITLE
ask for source code

### ISSUE THREAD

**Issue by SuYanqi** [siddhu001/Evaluating-Explanations#1]
Hi,

Recently, I read your paper, "Explain, Edit, and Understand: Rethinking User Study Design for Evaluating Model Explanations". I'm very interested in your paper. Could you please share your code with me?

Thanks very much!

**Comment by siddhu001** [comment]
Hi @SuYanqi 

Thanks a lot for your interest! I am sorry for the late reply, I have been away on vacation.

We are currently working on it and plan to make the code publicly available by early August.

Best Regards,
Siddhant Arora

**Comment by siddhu001** [comment]
Hi @SuYanqi

The source code has been made public now!
